### ISSUE TITLE
아.. 이건 사기에요

### ISSUE THREAD

**Issue by sangdo913** [Dinoryong/algo-dinner#8]
https://github.com/Dinoryong/algo-dinner/blob/a5b2c0dd3f5ff85b46a42c2e99ab36b649aa33b2/SEASON_3/Implement%20strStr()/geonuk_Implement%20strStr().java#L3

사기 금지 금지
@parkgunuk

**Comment by parkgunuk** [comment]
반려드립니다. @sangdo913
